[build]
  base = "docs/"
  publish = "docs/public"
  command = "yarn build"

[[plugins]]
  package = "netlify-plugin-checklinks"

  [plugins.inputs]
    checkExternal = true

    skipPatterns = [
      ".*inline Css.*"
    ]
